### ISSUE TITLE
Sort out SmartPort calls

### ISSUE THREAD

**Issue by inexorabletash** [inexorabletash/a2d#100]
The SmartPort calls from `desktop_main.s` do a convoluted dance to compute control unit numbers from ProDOS unit numbers, and it still doesn't seem to work. E.g. before a STATUS call:

```
        lda     unit_number
        pha
        rol     a
        pla
        php
        and     #$20
        lsr     a
        lsr     a
        lsr     a
        lsr     a
        plp
        adc     #1
        sta     status_unit_num
``` 
... which seems to produce this mapping:
```
;;; S0D1 = N/A                                                                                      
;;; S1D1 = 0001xxxx => 0001 = 1                                                                    
;;; S2D1 = 0010xxxx => 0011 = 3                                                                     
;;; S3D1 = 0011xxxx => 0011 = 3                                                                     
;;; S4D1 = 0100xxxx => 0001 = 1                                                                     
;;; S5D1 = 0101xxxx => 0001 = 1                                                                     
;;; S6D1 = 0110xxxx => 0011 = 3                                                                     
;;; S7D1 = 0111xxxx => 0011 = 3                                                                     
;;; S0D2 = N/A                                                                                      
;;; S1D2 = 1001xxxx => 0010 = 2                                                                     
;;; S2D2 = 1010xxxx => 0100 = 4                                                                     
;;; S3D2 = 1011xxxx => 0100 = 4                                                                     
;;; S4D2 = 1100xxxx => 0010 = 2                                                                     
;;; S5D2 = 1101xxxx => 0010 = 2                                                                     
;;; S6D2 = 1110xxxx => 0100 = 4                                                                     
;;; S7D2 = 1111xxxx => 0100 = 4                 
```

WAT?? I know the code generally doesn't understand SmartPort remapping done by ProDOS... but the above is just strange. Treating drive 1/2 as unit number 1/2 would at least make some sense, but WTF is going on with the above code?

Anyway... I asked on [CSA2P](https://groups.google.com/d/topic/comp.sys.apple2.programmer/Sa6fMbCZxos/discussion) and despite answers from qkumba and @mgcaret I'm still confused. For example, qkumba wrote:

> For the first four SmartPort partitions, the unit numbers are the same between ProDOS and SmartPort, and can be read directly by calling $Cx0A.  The SmartPort interface will make the translation for you to convert the unit number to the device number.

From debugging using Virtual II, trying to talk to SmartPort devices in Slot 7 requires issuing the calls with control unit numbers 1 and 2. So "unit numbers are the same... interface will make the translation for you" doesn't make sense. 

I've corrected the logic that assumes ProDOS unit number gives an actual slot, and instead , but that's somewhat moot if the SP calls are fundamentally bogus...

**Comment by mgcaret** [comment]
> On Dec 28, 2018, at 9:22 PM, Joshua Bell <notifications@github.com> wrote:
> 
> The SmartPort calls from desktop_main.s do a convoluted dance to compute control unit numbers from ProDOS unit numbers, and it still doesn't seem to work. E.g. before a STATUS call:
> 
>         lda     unit_number
>         pha
>         rol     a
>         pla
>         php
>         and     #$20
>         lsr     a
>         lsr     a
>         lsr     a
>         lsr     a
>         plp
>         adc     #1
>         sta     status_unit_num
> ... which seems to produce this mapping:
> 
> ;;; S0D1 = N/A                                                                                      
> ;;; S1D1 = 0001xxxx => 0001 = 1                                                                    
> ;;; S2D1 = 0010xxxx => 0011 = 3                                                                     
> ;;; S3D1 = 0011xxxx => 0011 = 3                                                                     
> ;;; S4D1 = 0100xxxx => 0001 = 1                                                                     
> ;;; S5D1 = 0101xxxx => 0001 = 1                                                                     
> ;;; S6D1 = 0110xxxx => 0011 = 3                                                                     
> ;;; S7D1 = 0111xxxx => 0011 = 3                                                                     
> ;;; S0D2 = N/A                                                                                      
> ;;; S1D2 = 1001xxxx => 0010 = 2                                                                     
> ;;; S2D2 = 1010xxxx => 0100 = 4                                                                     
> ;;; S3D2 = 1011xxxx => 0100 = 4                                                                     
> ;;; S4D2 = 1100xxxx => 0010 = 2                                                                     
> ;;; S5D2 = 1101xxxx => 0010 = 2                                                                     
> ;;; S6D2 = 1110xxxx => 0100 = 4                                                                     
> ;;; S7D2 = 1111xxxx => 0100 = 4                 
> WAT?? I know the code generally doesn't understand SmartPort remapping done by ProDOS... but the above is just strange. Treating drive 1/2 as unit number 1/2 would at least make some sense, but WTF is going on with the above code?
> 
> Anyway... I asked on CSA2P <https://groups.google.com/d/topic/comp.sys.apple2.programmer/Sa6fMbCZxos/discussion> and despite answers from qkumba and @mgcaret <https://github.com/mgcaret> I'm still confused. For example, qkumba wrote:
> 
> For the first four SmartPort partitions, the unit numbers are the same between ProDOS and SmartPort, and can be read directly by calling $Cx0A. The SmartPort interface will make the translation for you to convert the unit number to the device number.
> 
> From debugging using Virtual II, trying to talk to SmartPort devices in Slot 7 requires issuing the calls with control unit numbers 1 and 2. So "unit numbers are the same... interface will make the translation for you" doesn't make sense.
> 
> I've corrected the logic that assumes ProDOS unit number gives an actual slot, and instead , but that's somewhat moot if the SP calls are fundamentally bogus...
> 
> 


Well, it works for slot 5 unit 3 and 4 remapping to slot 2, which is the only kind of remapping that was supported under ProDOS 1.x.  If ProDOS had ever allowed slot 4->slot 1 remapping (which is theoretically possible with correctly-written firmware), it would be broken.


MG
