### ISSUE TITLE
DeskTop should be able to launch DAs like other applications.

### ISSUE THREAD

**Issue by mgcaret** [inexorabletash/a2d#101]
This feature would allow launching D.A.s from a folder, (e.g. one named "Control.Panels" that housed D.A.s that were more control-panel like).  It would also allow for more than 14 D.A.s to be used by making them launchable by an alternate method.

**Comment by mgcaret** [comment]
Additionally related, a small header in a DA might be able to give metadata, such as an icon to use, that a "Preview" DA could make use of, if present.

**Comment by mgcaret** [comment]
Another related, if a DA can register as a file type handler, maybe it could also opt-out of being on the menu?  E.g. if there were DAs that configured accelerators on an Apple IIe Card, Zip Chip, FastChip, and TransWarp, they could opt out of the menu if their respective hardware was not present.

**Comment by inexorabletash** [comment]
As an intermediate step, I've got a branch that refractors the DA launching code to take a pathname. That could be used to launch DAs with minimal additions. 

It also introduces a `Preview/` dir and moves the Show XXX Files DAs there, and adds support to the launching logic (used by double-click/File > Open) for TXT/FOT files, using hardcoded paths (`preview/show.text.file`, etc)

This could be generalized by using a file name scheme (e.g. `PREVIEW.XX`).

**Comment by inexorabletash** [comment]
FWIW, launching DAs is as simple as:
```diff
--- a/desktop/desktop_main.s
+++ b/desktop/desktop_main.s
@@ -946,6 +946,10 @@ begin:
         bne     :+
         addr_jump invoke_desk_acc, str_preview_txt
 
+:       cmp     #$F1
+        bne     :+
+        addr_jump invoke_desk_acc, path
+
 :       lda     #ERR_FILE_NOT_OPENABLE
         jsr     show_alert_and_fail
```

... but the $F1 file type is overloaded. DAs use AuxType $640 (or $8640), so that could be checked. And then we'd want a specific icon e.g. see #116

**Comment by inexorabletash** [comment]
Done. DA files now get the "Apple file" icon, and can be executed directly.
