### ISSUE TITLE
D.A.s with the aux type high bit set should not be added to menu.

### ISSUE THREAD

**Issue by mgcaret** [inexorabletash/a2d#102]
This "disable" bit is similar to how GS/OS enables/disables various drivers/extensions/etc.  This would allow a user to choose which D.A.s appeared in the menu without copying/moving them around.  A theoretical manager D.A. could toggle the bit (and maybe re-load the menu) for individual D.A.s.

**Comment by inexorabletash** [comment]
Easy peasy.

**Comment by c0mmander8** [comment]
Can you not add to the Apple menu all other file types and folders that have their aux type high bit set?

**Comment by c0mmander8** [comment]
Can you disable from the Apple menu all other file types and folders that have their aux type high bit set?

**Comment by inexorabletash** [comment]
Changing the aux type of arbitrary files would break them. For example, for binary files, the aux type is the load address. Just don't put files in the folder if you don't want them to appear. 

Please don't repeat your comments.

**Comment by c0mmander8** [comment]
What about folders?
