### ISSUE TITLE
Disassemble RAM.SYSTEM

### ISSUE THREAD

**Issue by inexorabletash** [inexorabletash/a2d#108]
MouseDesk 2.0 (but not Apple II DeskTop!) came with `RAM.SYSTEM`, a RAM Disk driver for RamWorks. When launched, it would probe for RamWorks banks and if found install a device (Slot 3 Drive 1), then chain to `/MOUSE.DESK/MD.SYSTEM` (if present)

This is a generally useful utility, and should be included in the disassembly work.

**Comment by inexorabletash** [comment]
Ongoing in the `ram.system/` directory. 

The disassembly is mostly complete. What's lacking is the formatting logic (which is obviously setting up the volume bitmap, but I'm a bit clueless on details) and the logic of the driver itself.

Of note: a maximum of 24 banks will be used for the ramdisk. I'm not sure if this limitation emerges from the code, or if it's just arbitrary.

**Comment by mgcaret** [comment]
L2048 is probably used to reserve banks for AppleWorks and other applications. This is a typical feature of auxmem ramdisk drivers. 

You tell the driver to reserve that many banks, and patch AppleWorks to use no more than that. 

MG

**Comment by MarcoVerpelli** [comment]
Hi,
this program has already been disassembled and commented by Deckard.
http://boutillon.free.fr/Underground/Outils/Ram_Drv_System/Ram_Drv_System.html
I hope French is not a problem ;)

Marco

**Comment by inexorabletash** [comment]
Thanks @MarcoVerpelli !

**Comment by inexorabletash** [comment]
Should we nuke this from the repo since it's an independent project?

**Comment by inexorabletash** [comment]
I copied my disassembly work to a new repo:

https://github.com/inexorabletash/ram.system

**Comment by mgcaret** [comment]
I agree that's probably the best place to home it.
