### ISSUE TITLE
Opening a DHR FOT image just results in "Please insert the system disk."

### ISSUE THREAD

**Issue by tomcw** [inexorabletash/a2d#125]
From https://github.com/AppleWin/AppleWin/issues/523

I said:
>I do have a disk with an FOT file (and I can see the new icon), but when I double click it I just get a dialog box saying "Please insert the system disk."

You said:
>Was the A2D volume still accessible? That alert would show if it's not. A2D is trying to load PREVIEW/SHOW.IMAGE.FILE relative to A2D to actually do the preview - overlays and accessories are loaded on the fly. A2D basically needs the volume to remain mounted for smooth operation.

**Comment by tomcw** [comment]
To reproduce this:

I'm using AppleWin 1.28.1 (model=Enhanced //e), RAMworks 127x64K banks (-r 127), mousecard in slot-4.

I have your A2DeskTop.po ("1.2 Pre Alpha 0") disk in S7D1.
And boot with this ProDOS disk in S6D1: "Apple Ext80ColumnAppleColorCardHR Demo 2.dsk"
(Hold down left-ALT when booting to skip the HDD firmware from  booting from S7)

From the command prompt:
```
] PREFIX /A2.DESKTOP
] - DESKTOP.SYSTEM
```

Open the AppleColor volume.
Open Rodent, and I get this error:
![applecolor-rodent-error](https://user-images.githubusercontent.com/6696896/52240381-93d08f80-28c8-11e9-978c-b069c748283e.png)

**Comment by tomcw** [comment]
NB. The AppleColor...2.dsk is here:
http://mirrors.apple2.org.za/Apple II Documentation Project/Interface Cards/Apple IIe/Apple IIe Extended 80 Column RGB Card/Disk Images/

**Comment by tomcw** [comment]
Hmm... that floppy has ProDOS 1.0.1 1-JAN-84 on it... too old perhaps?

**Comment by tomcw** [comment]
Yes, that was it. I tried with "ProDOS 8 V2.0.3      06-May-93" and that worked!
I'll close this issue.

**Comment by inexorabletash** [comment]
Thanks for diagnosing!

Interesting that only that functionality fails. I should do a compatibility pass and fail the startup after a version check of its not fixable.

**Comment by inexorabletash** [comment]
Ah, probably "Removed the check for the ProDOS version number from the OPEN routine." changed in 1.1. The use of GS/OS filename case bits in the version fields would do it.
