### ISSUE TITLE
Revise menu items / keyboard shortcuts

### ISSUE THREAD

**Issue by inexorabletash** [inexorabletash/a2d#13]
The existing menu items have (by modern standards) unusual names and non-intuitive shortcuts.

Examples:

* [ ] "Rename an Icon..." - why not just "Rename..." ?

Others...?

**Comment by inexorabletash** [comment]
Current:

* Apple
  * About Apple II Desktop
  * _(separator)_
  * Desk Accessory N
  * ...
* File
  * New Folder ...
  * _(separator)_
  * Open
  * Close
  * Close All
  * Select All
  * _(separator)_
  * Copy a File ...
  * Delete a File ...
  * _(separator)_
  * Eject
  * Quit
* View
  * By Icon
  * By Name
  * By Date
  * By Size
  * By Type
* Special
  * Check Drives
  * _(separator)_
  * Format a Disk ...
  * Erase a Disk ...
  * Disk Copy ...
  * _(separator)_
  * Lock ...
  * Unlock ...
  * _(separator)_
  * Get Info ...
  * Get Size ...
  * _(separator)_
  * Rename an Icon ...
* Startup
  * Slot N
  * ...
* Selector
  * Add an Entry ...
  * Edit an Entry ...
  * Delete an Entry ...
  * Run an Entry ..
  * _(separator)_
  * Entry N
  * ...

**Comment by inexorabletash** [comment]
Proposed (still noodling)

* File
  * New Folder ...
  * _(separator)_
  * Open
  * Close
  * Close All
  * Select All
  * _(separator)_
  * Get Info ...
  * Get Size ...
  * Rename ...
  * _(separator)_
  * Copy a File ...
  * Delete a File ...

* Special
  * Check Drives
  * Eject
  * _(separator)_
  * Format a Disk ...
  * Erase a Disk ...
  * Disk Copy ...
  * _(separator)_
  * Lock ...
  * Unlock ...
  * _(separator)_
  * Quit

**Comment by I3arana** [comment]
Yes , Looking a bit Different there, I vote for remove 'a' in items eg Erase a disk to Erase Disk... and some of the std shortcuts displayed in menu, eg apple O etc 
Would an edit menu (and its asociated clipboard) be of benefit, or hog memory?
