### ISSUE TITLE
Open volume/folder shading exp

### ISSUE THREAD

**Issue by inexorabletash** [inexorabletash/a2d#134]
(Already fixed, but I wanted to track this retroactively.)

The "shading" used to indicate a volume or folder is open is rendered as a rect. Note the "Tmp" folder:

![image](https://user-images.githubusercontent.com/771547/53303721-c3691c80-3822-11e9-89e0-2effa5239aa7.png)

This affects volume icons too, but they are mostly rectangular (except network shares) so it's harder to see.

**Comment by inexorabletash** [comment]
Fixed in 17184ec4d2dfbb7c240528cc8085d787c54b2d31

![image](https://user-images.githubusercontent.com/771547/53303760-2eb2ee80-3823-11e9-85d1-a617e4cf174d.png)

The new code also uses exactly the same path for desktop (volume) and windowed (file) icons.

**Comment by inexorabletash** [comment]
@mgcaret here's the file share icon in all four states:

![image](https://user-images.githubusercontent.com/771547/53303817-b26cdb00-3823-11e9-84e4-e6aeea9fd8d2.png)

No more residue afterwards, either.

**Comment by mgcaret** [comment]
That looks really good. 


--MG
