### ISSUE TITLE
Mouse moves trigger freezes on Laser 128 

### ISSUE THREAD

**Issue by inexorabletash** [inexorabletash/a2d#138]
When moving the mouse, DeskTop locks up on my Laser 128EX. This seems to happen regardless of accelerator state. I have not seen the behavior in Virtual ][ so I assume it is hardware specific. 

If I leave the mouse alone and just control DeskTop with keyboard shortcuts, I can use it for an arbitrary period of time without lockup's. But shortly after the mouse is moved the app will freeze. The time before this happens is shorter when accelerated - eg within a few seconds at 3x, within a minute at 1x. 

Something about interrupts, maybe?

**Comment by inexorabletash** [comment]
Debugging note: it appears the freeze does _not_ occur during an MGTK call (based on hacking MGTK to set a screen byte entry/exit).

**Comment by inexorabletash** [comment]
Debugging note: Hang is within `check_disks_in_devices`

**Comment by inexorabletash** [comment]
I tried moving the smartport relay call off the zero page, and swapping in ROM/main ZP. No change.

The SmartPort call in question is to the correct address; it's hitting $C70D which appears to be the correct entry point for slot 7; on my Laser that's the UDC controller and I have a FloppyEmu attached. The call is SmartPort STATUS against unit number 2. Everything looks okay. Trying a call from the monitor with the same params succeeds.

Also... this doesn't fail on the first call into `check_disks_in_devices` - I can see it succeed a few times before the failure. It's possible there's a bug in the Laser's UDC firmware, or a strange interaction with FloppyEmu.

**Comment by inexorabletash** [comment]
I just did what we did for the IIc+ slot 5 firmware - don't hammer a Laser 128's slot 7 SmartPort with STATUS calls. Seems to make my system rock solid now. Huzzah!

This might just be my machine (ROM version) and/or FloppyEmu... but the effects on other setups should be harmless - just need to manually refresh via Special > Check (All) Drive(s).

**Comment by mgcaret** [comment]
Did it do this before my IRQ commit?

**Comment by inexorabletash** [comment]
Yeah, the behavior is not new
