### ISSUE TITLE
Do something useful on Ctrl+Reset

### ISSUE THREAD

**Issue by inexorabletash** [inexorabletash/a2d#141]
Right now A2D just crashes into the monitor. Doing something better would be nice, e.g. just running the equivalent of File > Quit

One wrinkle: at least under Virtual ][ I don't see memory getting reset to Main, so Aux could still be active, and indeed the $3F2 vector is coming from aux.

Do we need to have an Aux reset handling routine that trampolines back to Main, or is Virtual ][ buggy?

**Comment by inexorabletash** [comment]
Looking at docs, posts, and the AppleWin source... I think this is a bug in the Virtual ][ //e emulation. I'll write a test routine before submitting a bug report.

**Comment by mgcaret** [comment]
There are other side effects to Ctrl+Reset in some configurations... Apple //e and IIgs with AppleTalk lose access to mounted volumes, so File->Quit is probably the best bet.

**Comment by inexorabletash** [comment]
Hmm... GSport/GSplus didn't behave as I expected either... will Main bank in correctly after Ctrl+Reset on the //e and IIgs, or does that need to be handled?

All I did was add this:
```asm
        copy16  #desktop_main::cmd_quit, RESETVEC
        jsr     SETPWRC
```
...right after the entry point at 800 in desktop_main.s

**Comment by mgcaret** [comment]
Sather (https://ia800702.us.archive.org/18/items/Understanding_the_Apple_IIe/Understanding_the_Apple_IIe_text.pdf <https://ia800702.us.archive.org/18/items/Understanding_the_Apple_IIe/Understanding_the_Apple_IIe_text.pdf> page 5-22) says that main RAM is enabled after reset on the //e.

I don’t have documentation on the //gs behavior, but I expect it is the same.

OTOH, since emulators are not doing this, maybe it should be handled anyway.

MG

**Comment by inexorabletash** [comment]
Okay, so fun times:

Any combination of RAMRDXX, RAMWRTXX, and ALTZPXX can be present on reset, in Virtual ][ at least, e.g. if MGTK is in the middle of drawing. So we'd need reset handler to be present at the same location in both main and aux. There's room for one at $3D0 at least (currently padding in `invoker.s`).

 So set both the aux and main reset vector ($3F2-$3F4) to point at $3D0 (plus the signature byte) and make sure $3D0 has this in both main and aux::
```asm
   ;; Get back to DeskTop Main expectations:
   sta RAMRDOFF
   sta RAMWRTOFF
   sta ALTZPON
   ;; Restore/invoke the quit handler
   jmp cmd_quit
```
... and this works just fine. 

_However..._ it turns out that just setting the reset vector ($3F2-$3F4) in Aux - even if no other bytes are touched - is enough to make the FORMAT call to the /RAM driver hang! So reset is handled, but now invoking other programs will hit the hang. _Ugh._

So... at least those aux bytes on page 3 would need to be saved/restored. Not sure what else, but this has been lots of not fun.
