### ISSUE TITLE
Add "Cycle Through Windows" command

### ISSUE THREAD

**Issue by inexorabletash** [inexorabletash/a2d#143]
Apple-` perhaps.

Suggested by Jay Edwards.

**Comment by inexorabletash** [comment]
Wrinkle: under Virtual ][, OpenApple-` cycles windows and Option-` is a "dead key" (as a way to insert accented characters like è).

Also, one of the select-and-activate-window routines paints the window twice. Otherwise... it's easy.

**Comment by c0mmander8** [comment]
Please reopen this issue, and as referenced in issue #154, make the Shift-Apple-` and Shift-Apple-Tab keypresses cycle backwards through open windows.
