### ISSUE TITLE
Double-click to open volume/folder fails

### ISSUE THREAD

**Issue by MarcoVerpelli** [inexorabletash/a2d#146]
Hello,
Okay, I know, I've been warned that it's not for the general public, but ...

The syntax of the pathname is invalid

if I double click on a disk icon, no problem via the File -> Open menu or if I use the keyboard shortcut,

Thank you.

Marco

**Comment by inexorabletash** [comment]
I assume this doesn't happen with the previous release, but otherwise same setup? Does the same thing happen with folders?

I may have broken something in recent changes and failed to test double-click (since accelerated emulators are not double-click friendly). 

I'll try and repro later today.

**Comment by MarcoVerpelli** [comment]
No, dosen't happen with previous version.
Yes same setup, and no double click on folder works.

You can reproduce with AppleWin, set CPU speed = 1Mhz and disk speed = authentic
although I don't think disk speed makes much difference, but these are my standard settings

Marco

**Comment by inexorabletash** [comment]
Updated build in https://github.com/inexorabletash/a2d/releases/tag/v1.2-prealpha3
