### ISSUE TITLE
Disk Copy freezes in 1.2

### ISSUE THREAD

**Issue by inexorabletash** [inexorabletash/a2d#147]
Reported on FaceBook, no other details.

**Comment by skanderbenabdelkrim** [comment]
Hi.
Another little issue when I try to boot on the disk is no prodos on the disk ("Unable to load Prodos").
Thanks

**Comment by inexorabletash** [comment]
Unrelated issue. It's not packaged with ProDOS in the image when autogenerated.

**Comment by inexorabletash** [comment]
I updated the 1.2-prealpha3 image w/ ProDOS/BASIC.system
