### ISSUE TITLE
Make Apple-W shortcut for Close Window

### ISSUE THREAD

**Issue by inexorabletash** [inexorabletash/a2d#154]
Apple-W is the "Close Window" on macOS Finder and IIgs Finder. Might as well align.

Currently, Apple-W initiates window selection mode; this is now redundant with Apple-Tab (or Apple-`) to cycle windows. There's no way to cycle backwards, though.

**Comment by c0mmander8** [comment]
Please, as referenced in issue #143, make the Shift-Apple-` and Shift-Apple-Tab keypresses cycle backwards through open windows.
