### ISSUE TITLE
MGTK has broken keyboard mouse shortcut

### ISSUE THREAD

**Issue by inexorabletash** [inexorabletash/a2d#155]
In DeskTop, if you hold Open- and Solid-Apple there is a beep and everything freezes until the modifiers are released. 

This is MGTK trying to start KeyboardMouse mode. Usually though, the mode is immediately exited. Sometimes (???) you can get it to stick, and steer the cursor around with arrow keys and click with the Apple keys. 

This is shortcut is not documented in the MGTK references, and since it's broken it's not really useful. It also prevents using double-modifiers for shortcuts (eg Close > Close All, Open > Open and Close Parent). 

There is an explicit KeyboardMouse command that apps can use to trigger this mode. 

Given all of that, I'm tempted to first fix the immediate exit problem, but then disable the activation logic.

**Comment by inexorabletash** [comment]
It's not broken, just didn't match my expectations.

Mouse Keys mode:

* To enter Mouse Keys mode, hold down the Open Apple key and then press and release the Solid Apple key.
* While holding Open Apple down, you can you can navigate the cursor with the arrow keys, and click using the Solid Apple key.
* To exit Mouse Keys mode, release the Open Apple key.

**Comment by eschaton** [comment]
Would you consider Mouse Keys to be an “accessibility” mode? If so then it could be adapted to work like Easy Access, which would stop usurping double-modifiers, as well as probably improve usability by not requiring Open Apple be held down.

**Comment by inexorabletash** [comment]
Yes, I think that would be an improvement. Rather than having MGTK do it, the app could define a more usable shortcut to enable/disable. 

I was in a rush and wanted to define the current behavior once I understood it, before embarking on bigger changes.
