### ISSUE TITLE
Eyes DA Crashes on IIc+

### ISSUE THREAD

**Issue by inexorabletash** [inexorabletash/a2d#157]
Not consistently, but on 3 out of 4 cold boots the Eyes DA crashed when redrawing, either on initial display or when the window was moved. 

This DA calls into Applesoft to do some trigonometry so possibly there are zero page or bank switching differences for this hardware. 

@mgcaret - have you seen this?

**Comment by mgcaret** [comment]
Haven’t noticed it.  I’ll see if I can reproduce.

Zero page for AppleSoft and bank switching should be identical to the original //c.

MG
