### ISSUE TITLE
Calculator: DeskTop icons not redrawn if dragged to screen bottom

### ISSUE THREAD

**Issue by inexorabletash** [inexorabletash/a2d#33]
Discovered via code inspection (_yay!_)

**Repro:**
1. Launch Calculator DA (via Apple menu)
2. Drag calculator window over a desktop icon (e.g. Trash, disks) and let go
3. Drag calculator to the bottom of the screen so that only the title bar is visible and let go

The icons fail to redraw.

This appears to be a bug in the code; after a drag the window position is checked and a flag is set if the top of the client area is below the screen. This flag could be used to avoid an unnecessary repaint if the client area is offscreen although it is not. Instead, the flag is used to skip repainting the desktop icons. But given the above repro steps this means the icons won't be redrawn given the above repro steps.

The optimization seems unnecessary, given how rarely it would be used in practice.

**Comment by inexorabletash** [comment]
![bug33](https://user-images.githubusercontent.com/771547/30571668-28d8f4e0-9c9e-11e7-819e-9d50faccb02f.png)

**Comment by inexorabletash** [comment]
It's not an optimization - window client area coordinates are incorrect if dragged below the screen (why?). But Calulator is just buggy; Puzzle is coded correctly.

**Comment by eric-ja** [comment]
Discovered an error code that can be returned from GetWinPort and BeginUpdate:
```
error_window_obscured := $A3
```

The DA's (and possibly Desktop itself?) do not seem to check for this error, thus using an invalid port.

**Comment by inexorabletash** [comment]
@eric-ja - Bingo! Yes, the DAs can use that.

I needed to use it here:

https://github.com/inexorabletash/a2d/blob/master/desk.acc/this.apple.s#L581

(Note that the DAs don't appear to be able to use update events due to the need to call into  JUMP_TABLE_REDRAW_ALL)

**Comment by inexorabletash** [comment]
Fixed in `fixed` branch.
