### ISSUE TITLE
Support DHGR Mono

### ISSUE THREAD

**Issue by inexorabletash** [inexorabletash/a2d#41]
See https://github.com/AppleWin/AppleWin/issues/523

Some non-Apple 80 column cards with DHR support allowed software control of DHGR monochrome vs. color. (My Laser 128EX has a hardware switch, some monitors had color killer buttons.)

Since A2D assumes monochrome, might as well try to support this for emulators/hardware that can be forced into monochrome mode while A2D is running. It seems like it's a combination of softswitches then remembering to set/clear the otherwise unused high bit.

This would likely require changes to the GUI library (which may leave the high bits in a random state; need to inspect all the code) and anything like the (new) Image Viewer DA that writes directly to the screen buffer.

**Comment by jvernet** [comment]
MOUSE DESK 2.0 French can use DHGR Mono mode of the Le Chat Mauve RGB Card. I remember that Apple II Desktop do not use this mode (see photo below, it's a IIgs color monitor, but connected to my Le Chat Mauve card)
So you may see if there is something interesting to use here.
![img_1187](https://user-images.githubusercontent.com/16312616/35533532-25146b06-053e-11e8-8d42-8362ac1dcbbd.JPG)
MOUSEPAINT do not use this mode
![img_1188](https://user-images.githubusercontent.com/16312616/35533671-8a2719f8-053e-11e8-85d0-a015afd61351.JPG)

**Comment by jvernet** [comment]
In fact, Mouse Desk 2.0 French I have is exactly the same as Apple II Desktop. Same dates, same authors. But Mouse Desk 2.0 French can use DHGR mono mode, Apple II Desktop seem to be unable.

**Comment by jvernet** [comment]
Sorry, it seems that I mistaken... JACE (wich emulate DGHR mono mode) show that every version of Apple Desktop I tried can handle mono mode....

**Comment by inexorabletash** [comment]
Do you have docs for the softswitches that control it?

The setup code pokes a few switches I haven't found docs on. They could be the ones controlling DHGR mono mode.

**Comment by jvernet** [comment]
You can find the card manual (in french) here:
[https://mirrors.apple2.org.za/ftp.apple.asimov.net/documentation/hardware/video/lechatmauve_eve_manuel_ocr.pdf](url)

Look at pages 117-118. The BW560 (560x192) mode is set with AN3 OFF, HR1 OFF, HR2 ON, HR3 ON 
Where:

AN3 : on $C05F off $C05E
HR1: on $COB3 off $COB2
HR2: on $COB5 off $COB4
HR3: on $COB7 off $COB6

**Comment by inexorabletash** [comment]
Looks promising. There is a sequence which pokes C0B5 and C0B7 along with other switches. Thanks for the link!

**Comment by inexorabletash** [comment]
Done for Show Image File DA in 06c721b4186891fca6a3f1f6d25137277492422f

Already supported by DeskTop, although there's still #43

**Comment by jvernet** [comment]
Applewin 1.28.1 support now this mode !

**Comment by inexorabletash** [comment]
I saw that! Need to try it out.
