### ISSUE TITLE
Show Image DA should clear/set NEWVIDEO B&W on IIgs

### ISSUE THREAD

**Issue by inexorabletash** [inexorabletash/a2d#44]
... so that images are in color, but the desktop is monochrome when DA exits.

**Comment by JohnMBrooks** [comment]
Related, Desktop does not reset NEWVIDEO B&W after the user exits a CDA/control panel. If the user has their preferences set to Color (very common), then Desktop goes blurry and the user has to go back to the control panel and change their prefs to monochrome (or restart Desktop).

Simple fix is to set NEWVIDEO in main loop.

**Comment by inexorabletash** [comment]
See also https://github.com/inexorabletash/a2d/issues/43

**Comment by inexorabletash** [comment]
Trying on real hardware: the screen jumps into lores mode and freezes. Double check the code?

**Comment by mgcaret** [comment]
Which real hardware?

Nothing jumps out at 1 AM, but the commentary on the NEWVIDEO register is incorrect wrt the _Technical Introduction to the IIgs_. Bit zero is the bank latch enable, used by the system.  NEWVIDEO should always be read/modified/written to avoid disturbing the bits that are not being changed.

**Comment by inexorabletash** [comment]
> Which real hardware?

I picked up a GS system (ROM 01 "Woz edition") for compat testing. My first GS so... some learning curve, and I don't have 100% confidence in the hardware.

> NEWVIDEO should always be read/modified/written to avoid disturbing the bits that are not being changed.

Thanks - that will probably do it. Not sure what I was referencing (I thought it was an Apple publication...)

**Comment by inexorabletash** [comment]
Yes, that fixed it.
