### ISSUE TITLE
New DA: Eyes

### ISSUE THREAD

**Issue by inexorabletash** [inexorabletash/a2d#53]
Like the classic XEyes, a:

* [x] movable
* [x] resizable
* [x] window that draws eyes that track the mouse

**Comment by inexorabletash** [comment]
![image](https://user-images.githubusercontent.com/771547/38848679-27f04c30-41bd-11e8-80b5-f263d62be926.png)

**Comment by JohnMBrooks** [comment]
Calculator, Calendar, and Puzzle are nice DAs too, but may not work with MGTK 1.0.

**Comment by inexorabletash** [comment]
> Calculator, Calendar, and Puzzle are nice DAs too, but may not work with MGTK 1.0.

@JohnMBrooks  - I'm not sure what you mean. The ones in various Asimov images work fine as-is in A2D 1.1 (latest we have, with MGTK 1.0.0F1); even better with the patches in `fixes` branch.

**Comment by JohnMBrooks** [comment]
Does Calculator work in A2D?

![image](https://user-images.githubusercontent.com/2241868/38852607-5e055db2-41cf-11e8-954e-4dadf6fa12e2.png)

**Comment by JohnMBrooks** [comment]
Calendar DA:

![image](https://user-images.githubusercontent.com/2241868/38852958-a191efc2-41d0-11e8-9646-cfe66bdabda3.png)

**Comment by inexorabletash** [comment]
These:

![calc](http://toastytech.com/guis/a2calc.gif)

![puzzle](http://toastytech.com/guis/a2puzzle.gif)

**Comment by JohnMBrooks** [comment]
Yes, that is rev 1.0 calculator, MGTK had another 3-4 years of improvements after 1.0.

**Comment by eric-ja** [comment]
@JohnMBrooks We are working with v1.0.0f1 of MGTK. Is there a later version? If so I think it would make sense to target it and then support 1.0.0f1 using conditional assembly.

**Comment by JohnMBrooks** [comment]
Apple's MGTK and the 80-col MouseText UI libs were used in lots of apps, most of which had releases many years after A2D. I'm not sure which app(s) used the latest rev of MGTK, but some WYSIWYG apps had releases into the early 90s:

BeagleWrite
![image](https://user-images.githubusercontent.com/2241868/38876846-233a92ae-4212-11e8-8162-c6cac1496475.png)

Publish.It4
![image](https://user-images.githubusercontent.com/2241868/38876675-d121cf50-4211-11e8-929b-a55ad4088a64.png)

MousePaint
![image](https://user-images.githubusercontent.com/2241868/38877103-d00ae65a-4212-11e8-9120-afbebfd8d022.png)

**Comment by inexorabletash** [comment]
Note to self: for resize, copy grow box bitmap from MGTK, paint it manually, do hit detection on it, and call GrowWindow. It doesn't look like MGTK cares if the window has the option but set.

**Comment by inexorabletash** [comment]
Note to others: maybe move discussion of MGTK versions to the mailing list sir a dedicated issue with a problem statement?

And for the other potential DAs - new bugs, with pointers to the apps that have them? (Expanding Calculator is easy-peasy, a Calendar seems fine, already have a bug for a text editor)

**Comment by inexorabletash** [comment]
Eyes DA still has a drawing glitch on startup some times (slash across the eye), but otherwise it's "feature complete"
