### ISSUE TITLE
Add master build script

### ISSUE THREAD

**Issue by inexorabletash** [inexorabletash/a2d#62]
... that combines the DeskTop segments

... and produces a disk image with everything including the DAs

**Comment by eric-ja** [comment]
How do you want to do the Makefiles? Recursive, monolithic ?

**Comment by inexorabletash** [comment]
Recursive is fine.

**Comment by inexorabletash** [comment]
At the top level:

* `res/go.sh` will invoke builds for the components (`desk.acc/*`, `desktop.system`, `desktop2`)
* `res/package.sh` will build an 800k image with everything

**Comment by inexorabletash** [comment]
Calling this done
