### ISSUE TITLE
RamWorks checker trashes memory, only handles contiguous banks

### ISSUE THREAD

**Issue by inexorabletash** [inexorabletash/a2d#66]
The checker in THIS.APPLE DA has issues:

* [ ] It writes signature bytes to $00, $01 in each bank to ensure the bank is live; if the memory is in use as a RAM disk it will be trashed. 
* [ ] The counter stops when the first non-live bank is found. This will skip some valid configurations, like sparsely populated cards.

**Comment by inexorabletash** [comment]
There's enough free main memory that we could spare a couple pages to stash/restore the original bytes, and the count algorithm is easily changed. But maybe there's a better way.

Also, not sure if we'll need to disable interrupts. (I confess I've never had a good handle on the practical requirements around interrupts in such cases.)

**Comment by mgcaret** [comment]
Ooh good point on the interrupts.  Probably a good idea to disable them.

I have written a routine that detects all banks, saving the checked locations on the stack, and only uses a few more bytes than the existing routine.  It's a bit slower due to the stack ops, but I doubt anyone will notice. :-)

I'll add the PHP SEI PLP combo and send a pull request.

**Comment by JohnMBrooks** [comment]
Does A2D use ramworks memory, or is it just counting banks so it can report the card's memory size?

**Comment by mgcaret** [comment]
It’s just counting banks.  Though an auxmem exstension mechanism would open up many possibilities...

**Comment by JohnMBrooks** [comment]
I've been working toward Ramworks support in ProDOS 2.5. I would be interested in discussing possible A2D use-cases to help steer P8 API.

**Comment by inexorabletash** [comment]
Just counting/reporting, for fun, in the "This Apple" DA I added recently. 

A2D will use a pre-existing RAMdisk at boot (copying itself plus apps listed as selector entries) but will not create one, and does not know how to use more than 128k of memory. 

(I should learn more about RamWorks-based RAMdisks - presumably there's a system file you can drop into the boot chain to get one? I only have experience with the Slinky one in my Laser.)

**Comment by inexorabletash** [comment]
Going further off topic: I'm starting to work on a slide deck giving an overview of A2D architecture. Will share when it's got more than placeholders.

**Comment by mgcaret** [comment]
RamWorks came with software to serve primarily two functions:  a RAM disk, and an AppleWorks extender.  One of them 'reserves' banks starting at the top of the card, the other 'reserves' banks from the bottom.   So if you have 16 banks, you could tell AppleWorks to use 4 of them, and the RAM disk to use the other 12.

The allocations are set by patching AppleWorks and the RAM disk .SYSTEM file.  There's no formalized allocation scheme.
