### ISSUE TITLE
What is DESKTOP1 ???

### ISSUE THREAD

**Issue by inexorabletash** [inexorabletash/a2d#70]
The bootstrap process has logic to write a file called `DESKTOP1`, file type $F!. This is also present as an 8k file on this disk image:

ftp://ftp.apple.asimov.net/pub/apple_II/images/masters/other_os/gui/A2Desktop.po

What is it?

**Comment by eric-ja** [comment]
Verbatim copy of DESKTOP.SYSTEM. Maybe to try to keep itself resident?

**Comment by inexorabletash** [comment]
The IIgs System 1.0 disk at ftp://ftp.apple.asimov.net/pub/apple_II/images/gs/os/gsos/System_1.0.zip only has `DESKTOP1` no `DESKTOP.SYSTEM`. The `DESKTOP.SYS16` application which the manual tells users to launch just sets the prefix to `/DeskTop` and invokes `DeskTop1`

So... likely the `DESKTOP.SYSTEM` file is a rename of `DESKTOP1` by whoever put together the disk image I initially downloaded, in order to make it the default SYSTEM file at startup.
