### ISSUE TITLE
Control Panel DA: Calibrate Joystick

### ISSUE THREAD

**Issue by inexorabletash** [inexorabletash/a2d#72]

**Comment by inexorabletash** [comment]
Rolled this into the Control Panel DA:

![image](https://user-images.githubusercontent.com/771547/49689327-794e8580-fad4-11e8-9505-4816aac4d42b.png)

Note: Only shows paddles 0 and 1 and buttons 0 and 1. Technically, there are 4 paddles and 3 buttons that could be shown. Anyone desperate for full fidelity?

**Comment by inexorabletash** [comment]
![image](https://user-images.githubusercontent.com/771547/50361809-dfe29300-0519-11e9-8ab9-906a747b220f.png)

Now shows all three buttons, but still only two paddles (x/y). Ideas:

* Show the next two paddles as vertical indicators, next to the x/y box
* Show an open circle on the x/y box representing the next two paddle inputs 

Slight usability nit: the 0/1/2 button indicators look exactly like the radio buttons, but aren't clickable. Could use a different bitmap for those.

**Comment by inexorabletash** [comment]
On my Laser, B2 always shows as checked and the DA lags horribly. Not positive it's the Joystick Calibration code, but likely - need to throttle the paddle reads or something.

**Comment by inexorabletash** [comment]
Locks up on IIc+

**Comment by inexorabletash** [comment]
Lockup fixed - loop to wait for a previous trigger to finish would never end if there was no joystick on real hardware. Added a timer.

**Comment by inexorabletash** [comment]
![image](https://user-images.githubusercontent.com/771547/62183930-e7201980-b310-11e9-9006-eefedeb0da0a.png)

**Comment by c0mmander8** [comment]
What happened to the original icon and to button 2 in Calibrate Joystick?

**Comment by inexorabletash** [comment]
The new icon better matches the symbol shown on the IIc back panel, and looks more elegant. 

Given how few devices expose more than two buttons it was unnecessary clutter.
