### ISSUE TITLE
This Apple DA: RamWorks memory reported as 16MB with no RW card

### ISSUE THREAD

**Issue by inexorabletash** [inexorabletash/a2d#78]
Someone on FB reports that on a stock Apple IIe w/ Extended 80 Column Card the memory is reported as 16MB rather than 128k.

From a quick scan of the code, it looks like the new `check_ramworks_memory` routine assumes that RWBANK will do something - either point at a populated bank, or a floating bus. But if it's a no-op then the normal (AUX) ZP will be present and the counter will increment.

**Comment by inexorabletash** [comment]
cc: @mgcaret 

The original (destructive) check avoided this.... hmm....

**Comment by inexorabletash** [comment]
Idea that comes to mind: do a dedicated test of bank 0 vs bank 1. Bank 0 must exist, so writes to bank 1 either succeed, float, or overwrite bank 0. In the latter case, no card is present.

**Comment by mgcaret** [comment]
That’s what I get for having a RamWorks in all my IIes... never occurred to me that there wouldn’t be one...
