### ISSUE TITLE
This Apple DA:  RamWorks bank count code still destructive.

### ISSUE THREAD

**Issue by mgcaret** [inexorabletash/a2d#80]
I just suddenly realized that the RamWorks bank test code that I contributed is still destructive.

We can't store anything on the stack because we've got ALTZP set, so the stack is the $0100 page in the bank we are testing... so writing to the stack corrupts the memory.  The additional code to discriminate a 16M RamWorks from no-RamWorks carries the same flaw.

I have an idea for a new implementation. Should have it done by tomorrow.

**Comment by inexorabletash** [comment]
Thanks for noticing this. 

Is there any reason we can't just stash the bytes in a "local" in main memory?

**Comment by JohnMBrooks** [comment]
Safest approach is to use 80store to read/write ramworks banks at either
$xx/0400 or $xx/2000, and save the original bank bytes at $00/6000-$00/60FF.

-JB

**Comment by inexorabletash** [comment]
I landed my version of a fix in 558753bdc8298e79a9b017cdb0c7803fef7c2577

**Comment by JohnMBrooks** [comment]
BTW, if the test code is banking in aux LC, then interrupts need to be
disabled first to avoid an IRQ vectoring through uninitialized 6502 vectors
in a ramworks bank.

Also, unpopulated ramworks banks 'wrap' to earlier banks, so the common
scan technique is to start at bank 255 and write the bank number to a fixed
byte location in descending bank order. Then count up from bank 0 until you
find a bank number mismatch which indicates the 'wrap' point.

-JB

**Comment by mgcaret** [comment]
I have a non-destructive fix written that doesn't need any scratch memory or the stack. I just need to test all the cases.  I believe it will turn out to be a few bytes shorter, as well.

**Comment by mgcaret** [comment]
This is my version, I haven't had time to do any testing of it.  If anyone wants to put eyeballs on it or put it through some paces, feel free.  Otherwise I will give it a work-through tomorrow.

```
.proc check_ramworks_memory
        sigb0   := $00
        sigb1   := $01

        ;; Run from clone in main memory
        php
        sei     ; don't let interrupts happen while the memory map is munged

        sta     RAMRDOFF
        sta     RAMWRTOFF

        ;; Assumes ALTZPON on entry/exit
        RWBANK  := $C073

        ldx     #0              ; bank we are checking
        ldy     #0              ; populated bank count
loop:   stx     RWBANK          ; select bank
        lda     sigb0           ; get first test location
        eor     #$ff            ; and complement it
        sta     sigb0           ; and put it back
        cmp     sigb0           ; floating bus unlikely to have this result
        bne     :+              ; no match, no bank
        eor     #$ff            ; restore original value
        sta     sigb0           ; and put back in RAM
        lda     sigb1           ; now do the same for second test location
        eor     #$ff
        sta     sigb1
        cmp     sigb1
        bne     :+              ; no match on second test
        eor     #$ff
        sta     sigb1
        iny                     ; second test passed, found a bank
:       inx                     ; next bank
        bne     loop            ; if we hit 256 banks, make sure we exit

        ;; Switch back to RW bank 0 (normal aux memory)
        lda     #0
        sta     RWBANK

        ;; --------------------------------------------------

        ;; Y=0 means either 256 populated banks, or that there was
        ;; never a RawWorks card present and RWBANK is a no-op.
        cpy     #0
        bne     done

        ;; Disambiguate these cases by writing to banks 0 and 1
        ;; and testing that they work. We know that bank 1 is
        ;; not an unpopulated RW bank.

        tax                     ; A is 0, use X for bank number we are testing
        lda     sigb0           ; we are at bank 0 already
        eor     #$FF
        sta     sigb0
        inx
        stx     RWBANK          ; go to bank 1
        cmp     sigb0           ; is it the same?
        beq     :+              ; if so keep testing
        dex                     ; if not, there is definitely a bank 1
        stx     RWBANK          ; so go back to bank 0, and see bailout below
:       eor     #$FF            ; restore original bank 0 value
        sta     sigb0           ; fix it (bank 0) or "fix" it (bank 1)
        dex
        bmi     done            ; there was a ramworks, X is now $FF
        stx     RWBANK          ; now back to bank 0
        cmp     sigb0           ; does bank 0 match original value now?
        bne     :+              ; no, so there is a ramworks
        iny                     ; flag one 64K aux bank, no ramworks
        bne     done       
:       sta     sigb0           ; restore original value
        inx
        stx     RWBANK
        eor     #$FF            ; recall that bank 1 tested as the complement
        sta     sigb0           ; and we "fixed" it, so actually fix it
        dex
        stx     RWBANK          ; back to bank 0, and we have a ramworks
        
        ;; Back to executing from aux memory
done:   sta     RAMRDON
        sta     RAMWRTON
        plp                     ; restore interrupt state
        rts
.endproc
```

**Comment by mgcaret** [comment]
> Also, unpopulated ramworks banks 'wrap' to earlier banks, so the common
scan technique is to start at bank 255 and write the bank number to a fixed
byte location in descending bank order. Then count up from bank 0 until you
find a bank number mismatch which indicates the 'wrap' point.

That has not been my experience.  If I load up a bank with 64K chips in a RamWorks, the missing banks read as floating bus. Same if I remove the chips for a bank entirely. 

That being said, an AE ramworks only supports a 7-bit bank value, so bank 128-255 are duplicates of the lower banks. So there may be a problem with the 8 MB ramworks-style cards out there. 

So we need a routine that:

- is non-destructive 
- detects all banks
- rejects duplicate banks

And while not a requirement, it’d be nice to avoid wasting 256 or 512 bytes of program space to save the test locations.  Perhaps there is a buffer we can borrow...

**Comment by mgcaret** [comment]
I guess we have $1B00-$1FFF in the main bank to use as we please... if that’s correct, then we go back to something like the original test that was as John describes, but save the overwritten locations, restoring them as we count up, and as we count up, we don’t stop at the first non-match.

Ref AE’s code:  http://ae.applearchives.com/apple_e/ramworks_iii/ramworks_iii_basic_manual_1.pdf

**Comment by inexorabletash** [comment]
$1C00-$1FFF  in the main bank is the io_buffer used when loading the DA, so it's definitely usable.

**Comment by inexorabletash** [comment]
Okay, one more try in 3a666316f329b952aa64fc548ef2b42c79006511

* Iterates down (bank $FF to $00), stashing bytes $0000 and $0001 at main $1C00,x/$1D00,x, and writing unique signatures (bank number/complement)
* Iterates up, comparing signatures; only restores if signature matches

This doesn't need the special "was there even a RW present?" check since that's handled by unique signatures per bank.

**Comment by mgcaret** [comment]
I like this one.   Looks perfect. 


--MG

**Comment by inexorabletash** [comment]
Thanks @JohnMBrooks and @mgcaret - closing this pending further data.
